const action = {
    Online: "Online",
    Draw_Offered: "Draw_Offered",
    Draw_Accepted: "Draw_Accepted",
    Draw_Rejected: "Draw_Rejected",
    Game_Resign: "Game_Resign",
    Illegal_Move: "Illegal_Move",
    Game_Clock: "Game_Clock",
    Opponent_Move: "Opponent_Move",
    Opponent_Left: "Opponent_Left",
    Opponent_Inactive: "Opponent_Inactive",
    Game_Started: "Game_Started",
    Game_Over: "Game_Over",
    Expired_Token: "Expired_Token",
    Search: "Search",
    Cancel_Search: "Cancel_Search",
    Move: "Move",
    Invalid_Request: "Invalid_Request",
    Rejoin: "Rejoin",
    Rejoin_Success: "Rejoin_Success",
    Rejoin_Failure: "Rejoin_Failure",
    Opponent_Rejoin: "Opponent_Rejoin",
    In_Check: "In_Check",
    Is_CheckMate: "Is_CheckMate",
    Is_StaleMate: "Is_Stalemate",
    Is_Draw: "Is_Draw",
    Is_ThreeFold: "Is_ThreeFold",
    Is_InsufficientMaterial: "Is_InsufficientMaterial",
    Is_Abandoned: "Is_Abandoned",
    Is_TimeUp: "Is_TimeUp",
    Player_Rating: "Player_Rating",
    Opponent_Rating: "Opponent_Rating",
    Opponent_Info: "Opponent_Info"
  };

module.exports = action;